# Generated by Django 6.0.2 on 2026-02-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 code', max_length=2, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=10)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('currency_symbol', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0, help_text='Display order')),
                ('default_timezone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['position', 'name'],
                'indexes': [models.Index(fields=['code'], name='core_countr_code_0b5501_idx'), models.Index(fields=['iso_code'], name='core_countr_iso_cod_9f5dac_idx'), models.Index(fields=['is_active'], name='core_countr_is_acti_9adcd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='State/Region code', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.country')),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'ordering': ['country', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, help_text='State or province (legacy field)', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_capital', models.BooleanField(default=False)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code prefix', max_length=20)),
                ('position', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country')),
                ('region', models.ForeignKey(blank=True, help_text='State/Region this city belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='core.region')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'region', 'position', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country', 'name'], name='core_region_country_2082cb_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['is_active'], name='core_region_is_acti_707308_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'country')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country', 'name'], name='core_city_country_174272_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region'], name='core_city_region__d69fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='core_city_is_acti_f34fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_capital'], name='core_city_is_capi_9530d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country', 'region')},
        ),
    ]
