# Generated by Django 6.0.2 on 2026-02-24 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_decimals', models.IntegerField(choices=[(2, '2 Decimal Places - Standard Retail (e.g., $19.99)'), (4, '4 Decimal Places - Wholesale/B2B (e.g., $15.4375)'), (6, '6 Decimal Places - High Precision (e.g., $0.052375)')], default=4, help_text='Number of decimal places for all prices across ERP')),
                ('cost_decimals', models.IntegerField(choices=[(2, '2 Decimal Places - Standard Retail (e.g., $19.99)'), (4, '4 Decimal Places - Wholesale/B2B (e.g., $15.4375)'), (6, '6 Decimal Places - High Precision (e.g., $0.052375)')], default=4, help_text='Number of decimal places for all costs across ERP')),
                ('default_currency', models.CharField(choices=[('USD', 'USD ($) - US Dollar'), ('EUR', 'EUR (€) - Euro'), ('GBP', 'GBP (£) - British Pound'), ('JPY', 'JPY (¥) - Japanese Yen'), ('INR', 'INR (₹) - Indian Rupee'), ('AUD', 'AUD (A$) - Australian Dollar'), ('CAD', 'CAD (C$) - Canadian Dollar'), ('CHF', 'CHF (Fr) - Swiss Franc'), ('CNY', 'CNY (¥) - Chinese Yuan'), ('BRL', 'BRL (R$) - Brazilian Real')], default='USD', max_length=3)),
                ('currency_position', models.CharField(choices=[('before', 'Before amount ($10.99)'), ('after', 'After amount (10.99€)'), ('before_space', 'Before with space ($ 10.99)'), ('after_space', 'After with space (10.99 €)')], default='before', max_length=20)),
                ('thousand_separator', models.CharField(choices=[('comma', 'Comma (1,000.00)'), ('period', 'Period (1.000,00)'), ('space', 'Space (1 000.00)'), ('none', 'None (1000.00)')], default='comma', max_length=10)),
                ('decimal_separator', models.CharField(default='.', help_text='Character used as decimal separator (. or ,)', max_length=1)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_website', models.URLField(blank=True)),
                ('company_tax_id', models.CharField(blank=True, help_text='VAT / Tax ID', max_length=100)),
                ('company_registration', models.CharField(blank=True, help_text='Company registration number', max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('date_format', models.CharField(choices=[('Y-m-d', '2024-12-31 (ISO)'), ('d/m/Y', '31/12/2024 (EU)'), ('m/d/Y', '12/31/2024 (US)'), ('d.m.Y', '31.12.2024 (EU dot)'), ('d-m-Y', '31-12-2024 (EU dash)')], default='Y-m-d', max_length=10)),
                ('time_format', models.CharField(choices=[('H:i', '14:30 (24 hour)'), ('h:i A', '02:30 PM (12 hour)')], default='H:i', max_length=10)),
                ('timezone_name', models.CharField(default='UTC', help_text='Server timezone', max_length=50)),
                ('fiscal_year_start', models.DateField(default=datetime.date(2026, 1, 1), help_text='Start date of fiscal year')),
                ('fiscal_year_end', models.DateField(default=datetime.date(2026, 12, 31), help_text='End date of fiscal year')),
                ('allow_negative_inventory', models.BooleanField(default=False, help_text='⚠️ Warning: Can cause accounting issues')),
                ('default_reorder_level', models.DecimalField(decimal_places=2, default=10.0, help_text='Default reorder level for new products', max_digits=10)),
                ('low_stock_threshold_percentage', models.IntegerField(default=20, help_text='Alert when stock falls below this % of reorder level')),
                ('invoice_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly (2024-0001, 2024-0002)'), ('monthly', 'Monthly (202412-0001, 202412-0002)'), ('custom', 'Custom pattern')], default='yearly', max_length=20)),
                ('sales_order_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly (2024-0001, 2024-0002)'), ('monthly', 'Monthly (202412-0001, 202412-0002)'), ('custom', 'Custom pattern')], default='yearly', max_length=20)),
                ('purchase_order_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly (2024-0001, 2024-0002)'), ('monthly', 'Monthly (202412-0001, 202412-0002)'), ('custom', 'Custom pattern')], default='yearly', max_length=20)),
                ('sku_pattern', models.CharField(choices=[('{CATEGORY}-{SEQUENCE}', 'CAT-0001 (by category)'), ('{BRAND}-{SEQUENCE}', 'BRAND-0001 (by brand)'), ('{CATEGORY}-{BRAND}-{SEQUENCE}', 'CAT-BRAND-0001 (combined)'), ('SKU-{SEQUENCE}', 'SKU-0001 (simple)'), ('manual', 'Manual entry only')], default='{CATEGORY}-{SEQUENCE}', max_length=50)),
                ('sku_length', models.IntegerField(default=8, help_text='Minimum SKU length')),
                ('customer_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly (2024-0001, 2024-0002)'), ('monthly', 'Monthly (202412-0001, 202412-0002)'), ('custom', 'Custom pattern')], default='yearly', max_length=20)),
                ('customer_prefix', models.CharField(default='CUST', help_text='Prefix for customer numbers', max_length=10)),
                ('vendor_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly (2024-0001, 2024-0002)'), ('monthly', 'Monthly (202412-0001, 202412-0002)'), ('custom', 'Custom pattern')], default='yearly', max_length=20)),
                ('vendor_prefix', models.CharField(default='VEND', help_text='Prefix for vendor numbers', max_length=10)),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_product_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ERP Global Settings',
                'verbose_name_plural': 'ERP Global Settings',
            },
        ),
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('products', 'Products Management'), ('inventory', 'Inventory Management'), ('sales', 'Sales & Customers'), ('purchasing', 'Purchasing & Vendors'), ('accounting', 'Accounting'), ('hr', 'Human Resources'), ('manufacturing', 'Manufacturing'), ('projects', 'Project Management'), ('reports', 'Reporting & Analytics')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('license_key', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['module'],
            },
        ),
    ]
