# Generated by Django 6.0.2 on 2026-03-03 20:09

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='VAT / Tax ID', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('fiscal_year_start', models.DateField(blank=True, help_text='Start date of fiscal year (e.g., Jan 1)', null=True)),
                ('fiscal_year_end', models.DateField(blank=True, help_text='End date of fiscal year (e.g., Dec 31)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rates_last_updated', models.DateTimeField(blank=True, help_text='When the exchange rate was last updated', null=True)),
                ('rate_update_source', models.CharField(blank=True, help_text="Where the rate came from (e.g., 'manual', 'ECB', 'openexchangerates')", max_length=100)),
                ('decimal_places', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=2)),
                ('decimal_separator', models.CharField(default='.', max_length=1)),
                ('thousand_separator', models.CharField(default=',', max_length=1)),
                ('symbol_position', models.CharField(choices=[('before', 'Before amount'), ('after', 'After amount')], default='before', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly Reset (2024-0001, 2024-0002)'), ('monthly', 'Monthly Reset (202412-0001, 202412-0002)')], default='yearly', max_length=20)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_next_number', models.PositiveIntegerField(default=1)),
                ('sales_order_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly Reset (2024-0001, 2024-0002)'), ('monthly', 'Monthly Reset (202412-0001, 202412-0002)')], default='yearly', max_length=20)),
                ('sales_order_prefix', models.CharField(default='SO', max_length=10)),
                ('sales_order_next_number', models.PositiveIntegerField(default=1)),
                ('purchase_order_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly Reset (2024-0001, 2024-0002)'), ('monthly', 'Monthly Reset (202412-0001, 202412-0002)')], default='yearly', max_length=20)),
                ('purchase_order_prefix', models.CharField(default='PO', max_length=10)),
                ('purchase_order_next_number', models.PositiveIntegerField(default=1)),
                ('customer_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly Reset (2024-0001, 2024-0002)'), ('monthly', 'Monthly Reset (202412-0001, 202412-0002)')], default='yearly', max_length=20)),
                ('customer_prefix', models.CharField(default='CUST', max_length=10)),
                ('customer_next_number', models.PositiveIntegerField(default=1)),
                ('vendor_numbering', models.CharField(choices=[('sequential', 'Sequential (0001, 0002, 0003)'), ('yearly', 'Yearly Reset (2024-0001, 2024-0002)'), ('monthly', 'Monthly Reset (202412-0001, 202412-0002)')], default='yearly', max_length=20)),
                ('vendor_prefix', models.CharField(default='VEND', max_length=10)),
                ('vendor_next_number', models.PositiveIntegerField(default=1)),
                ('pad_length', models.IntegerField(default=4, help_text='Zero-padding length for sequence number (4 = 0001)')),
            ],
            options={
                'verbose_name': 'Document Numbering',
                'verbose_name_plural': 'Document Numbering',
            },
        ),
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('products', 'Products Management'), ('inventory', 'Inventory Management'), ('sales', 'Sales & Customers'), ('purchasing', 'Purchasing & Vendors'), ('accounting', 'Accounting'), ('hr', 'Human Resources'), ('manufacturing', 'Manufacturing'), ('projects', 'Project Management'), ('reports', 'Reporting & Analytics')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('license_key', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, help_text='Module license expiry date. Module auto-disables on this date.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['module'],
            },
        ),
        migrations.CreateModel(
            name='ERPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_decimals', models.IntegerField(choices=[(2, '2 decimal places — Standard Retail ($19.99)'), (4, '4 decimal places — Wholesale/B2B ($15.4375)'), (6, '6 decimal places — High Precision ($0.052375)')], default=4)),
                ('cost_decimals', models.IntegerField(choices=[(2, '2 decimal places — Standard Retail ($19.99)'), (4, '4 decimal places — Wholesale/B2B ($15.4375)'), (6, '6 decimal places — High Precision ($0.052375)')], default=4)),
                ('currency_position', models.CharField(choices=[('before', 'Before amount ($10.99)'), ('after', 'After amount (10.99€)'), ('before_space', 'Before with space ($ 10.99)'), ('after_space', 'After with space (10.99 €)')], default='before', max_length=20)),
                ('thousand_separator', models.CharField(choices=[('comma', 'Comma  →  1,000.00'), ('period', 'Period →  1.000,00'), ('space', 'Space  →  1 000.00'), ('none', 'None   →  1000.00')], default='comma', max_length=10)),
                ('decimal_separator', models.CharField(default='.', max_length=1)),
                ('date_format', models.CharField(choices=[('Y-m-d', '2024-12-31 (ISO)'), ('d/m/Y', '31/12/2024 (EU)'), ('m/d/Y', '12/31/2024 (US)'), ('d.m.Y', '31.12.2024 (EU dot)'), ('d-m-Y', '31-12-2024 (EU dash)')], default='Y-m-d', max_length=10)),
                ('time_format', models.CharField(choices=[('H:i', '14:30 (24-hour)'), ('h:i A', '02:30 PM (12-hour)')], default='H:i', max_length=10)),
                ('timezone_name', models.CharField(default='UTC', max_length=50)),
                ('allow_negative_inventory', models.BooleanField(default=False, help_text='⚠️ Warning: allowing negative inventory can cause accounting issues')),
                ('default_reorder_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('low_stock_threshold_percentage', models.IntegerField(default=20, help_text='Alert when stock falls below this % of the reorder level')),
                ('sku_pattern', models.CharField(choices=[('{CATEGORY}-{SEQUENCE}', 'CAT-0001'), ('{BRAND}-{SEQUENCE}', 'BRAND-0001'), ('{CATEGORY}-{BRAND}-{SEQUENCE}', 'CAT-BRAND-0001'), ('SKU-{SEQUENCE}', 'SKU-0001'), ('manual', 'Manual entry only')], default='{CATEGORY}-{SEQUENCE}', max_length=50)),
                ('sku_length', models.IntegerField(default=8, help_text='Minimum SKU length')),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_product_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(blank=True, help_text='Default currency for the ERP', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erp_settings_default', to='config_settings.currency')),
            ],
            options={
                'verbose_name': 'ERP Global Settings',
                'verbose_name_plural': 'ERP Global Settings',
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_model', models.CharField(choices=[('single', 'Single Price (all customers same price)'), ('multi', 'Multi-Tier Pricing (different prices per customer type)')], default='single', max_length=10)),
                ('default_retail_name', models.CharField(default='Retail Price', max_length=50)),
                ('default_wholesale_name', models.CharField(default='Wholesale Price', max_length=50)),
                ('default_distributor_name', models.CharField(default='Distributor Price', max_length=50)),
                ('prices_include_tax', models.BooleanField(default=False, help_text='If True, all displayed prices are tax-inclusive')),
                ('rounding_rule', models.CharField(choices=[('standard', 'Standard (0.5 rounds up)'), ('always_up', 'Always round up'), ('always_down', 'Always round down (truncate)'), ('banker', "Banker's rounding (round half to even)")], default='standard', help_text='How to round calculated prices', max_length=20)),
                ('base_currency', models.ForeignKey(blank=True, help_text='Base currency for all pricing calculations', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_configs', to='config_settings.currency')),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='config_settings.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SettingsChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('erp_settings', 'ERP Settings'), ('company_profile', 'Company Profile'), ('pricing_config', 'Pricing Configuration'), ('currency', 'Currency'), ('module_status', 'Module Status'), ('doc_numbering', 'Document Numbering')], max_length=50)),
                ('setting_id', models.IntegerField(help_text='PK of the changed record')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['setting_type', '-changed_at'], name='config_sett_setting_6a6446_idx'), models.Index(fields=['changed_by', '-changed_at'], name='config_sett_changed_51188e_idx')],
            },
        ),
    ]
