# Generated by Django 6.0.2 on 2026-02-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_model', models.CharField(choices=[('single', 'Single Price (All customers same price)'), ('multi', 'Multi-Tier Pricing (Different prices per customer type)')], default='single', help_text='Choose pricing model for your business', max_length=10)),
                ('default_retail_name', models.CharField(default='Retail Price', max_length=50)),
                ('default_wholesale_name', models.CharField(default='Wholesale Price', max_length=50)),
                ('default_distributor_name', models.CharField(default='Distributor Price', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.AlterField(
            model_name='erpsettings',
            name='fiscal_year_end',
            field=models.DateField(blank=True, help_text='End date of fiscal year', null=True),
        ),
        migrations.AlterField(
            model_name='erpsettings',
            name='fiscal_year_start',
            field=models.DateField(blank=True, help_text='Start date of fiscal year', null=True),
        ),
    ]
