# Generated by Django 6.0.2 on 2026-02-26 19:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_settings', '0002_pricingconfig_alter_erpsettings_fiscal_year_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO currency code (USD, EUR, GBP)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(help_text='$, €, £', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate relative to base currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_base', models.BooleanField(default=False, help_text='Base currency for calculations')),
                ('is_active', models.BooleanField(default=True)),
                ('decimal_places', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=2)),
                ('decimal_separator', models.CharField(default='.', max_length=1)),
                ('thousand_separator', models.CharField(default=',', max_length=1)),
                ('symbol_position', models.CharField(choices=[('before', 'Before amount'), ('after', 'After amount')], default='before', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='config_settings.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
