# Generated by Django 6.0.2 on 2026-03-03 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_serial_tracking', models.BooleanField(default=False, help_text='Enable individual serial number tracking')),
                ('enable_batch_tracking', models.BooleanField(default=True, help_text='Enable batch/lot tracking with expiry dates')),
                ('enable_damaged_goods', models.BooleanField(default=False, help_text='Enable damaged goods recording')),
                ('enable_reservations', models.BooleanField(default=False, help_text='Enable stock reservations for sales orders')),
                ('enable_cycle_counting', models.BooleanField(default=False, help_text='Enable cycle counting workflow')),
                ('enable_auto_reorder', models.BooleanField(default=True, help_text='Enable automatic reorder alerts')),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average', 'Weighted Average'), ('standard', 'Standard Cost')], default='fifo', help_text='Default inventory valuation method', max_length=20)),
                ('reservation_expiry_hours', models.PositiveIntegerField(default=24, help_text='Hours after which unfulfilled reservations auto-release')),
                ('allow_backorders', models.BooleanField(default=False, help_text='Allow backorders when stock is insufficient')),
                ('require_writeoff_approval', models.BooleanField(default=True, help_text='Require manager approval for write-offs')),
                ('track_damage_reasons', models.BooleanField(default=True, help_text='Track reasons for damaged goods')),
                ('cycle_count_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('cycle_count_by', models.CharField(choices=[('section', 'By Section'), ('category', 'By Category'), ('value', 'By Value (ABC)')], default='section', max_length=20)),
                ('variance_threshold_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='Acceptable variance percentage before investigation', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Inventory Settings',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity on hand in base units', max_digits=10)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Number of base units per this unit', max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert when stock drops below this level', max_digits=10)),
                ('max_level', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum desired stock level', max_digits=10, null=True)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, help_text='Safety stock level', max_digits=10)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity reserved for sales orders', max_digits=10)),
                ('last_counted', models.DateTimeField(blank=True, null=True)),
                ('last_movement', models.DateTimeField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False, help_text='Prevent stock movements')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit')),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Unique batch/lot number', max_length=50, unique=True)),
                ('manufacturing_date', models.DateField(blank=True, help_text='Date of manufacture', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date of expiry', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in this batch', max_digits=10)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Number of base units per this unit', max_digits=10)),
                ('received_date', models.DateField(auto_now_add=True, help_text='Date batch was received')),
                ('supplier', models.CharField(blank=True, help_text='Supplier/vendor name', max_length=100)),
                ('supplier_batch', models.CharField(blank=True, help_text="Supplier's batch number", max_length=50)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quarantine', 'In Quarantine')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stock')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit')),
            ],
            options={
                'ordering': ['-expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('warranty', 'Under Warranty')], default='in_stock', max_length=20)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='products.product')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.stockbatch')),
            ],
        ),
        migrations.CreateModel(
            name='DamagedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_type', models.CharField(choices=[('shipping', 'Shipping Damage'), ('handling', 'Handling Damage'), ('storage', 'Storage Damage'), ('expired', 'Expired'), ('defective', 'Manufacturing Defect'), ('other', 'Other')], max_length=20)),
                ('disposition', models.CharField(choices=[('write_off', 'Write Off'), ('return_to_supplier', 'Return to Supplier'), ('sell_as_scrap', 'Sell as Scrap'), ('donate', 'Donate'), ('repair', 'Repair')], max_length=20)),
                ('description', models.TextField()),
                ('insurance_claim', models.BooleanField(default=False)),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_damages', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damages', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serialnumber')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_items', to='inventory.stock')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_items', to='inventory.stockbatch')),
            ],
            options={
                'verbose_name_plural': 'Damaged Goods',
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('count_type', models.CharField(choices=[('full', 'Full Physical Inventory'), ('cycle', 'Cycle Count'), ('spot', 'Spot Check')], default='full', max_length=20)),
                ('cycle_category', models.CharField(blank=True, help_text='Category/section being cycle counted', max_length=50)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('variance_approved', models.BooleanField(default=False)),
                ('variance_approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_counts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('variance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_variances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_reference', models.CharField(help_text='Sales Order #', max_length=100)),
                ('order_line_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('warehouse_type', models.CharField(choices=[('main', 'Main Warehouse'), ('branch', 'Branch'), ('cold_storage', 'Cold Storage'), ('third_party', 'Third Party'), ('dropship', 'Drop Shipping'), ('crossdock', 'Cross Dock')], default='main', max_length=20)),
                ('temperature_zone', models.CharField(choices=[('ambient', 'Ambient (15-25°C)'), ('cool', 'Cool (8-15°C)'), ('cold', 'Cold (2-8°C)'), ('frozen', 'Frozen (-18 to -25°C)'), ('hazardous', 'Hazardous Materials')], default='ambient', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Optional capacity in base units', max_digits=12, null=True)),
                ('utilization_threshold', models.DecimalField(decimal_places=2, default=85.0, help_text='Alert when utilization exceeds this percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours in JSON format')),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_capacities', to='products.unit')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity_fulfilled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20)),
                ('aisle', models.CharField(max_length=20)),
                ('rack', models.CharField(max_length=20)),
                ('bin', models.CharField(max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('max_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum capacity for this section', max_digits=10, null=True)),
                ('current_occupancy', models.DecimalField(decimal_places=2, default=0, help_text='Current occupancy in base units', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Warehouse Sections',
                'ordering': ['warehouse', 'zone', 'aisle', 'rack', 'bin'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return'), ('DAMAGE', 'Damage/Written Off'), ('COUNT', 'Stock Count')], max_length=20)),
                ('source', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sales Issue'), ('transfer', 'Warehouse Transfer'), ('adjustment', 'Manual Adjustment'), ('return', 'Return'), ('damage', 'Damage/Written Off'), ('count', 'Stock Count'), ('production', 'Production'), ('assembly', 'Assembly')], default='adjustment', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, help_text='Reference document (PO, SO, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.warehousesection')),
            ],
            options={
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockcount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='inventory.warehousesection'),
        ),
        migrations.AddField(
            model_name='stock',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='inventory.warehousesection'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousesection'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['batch_number'], name='inventory_s_batch_n_3f0960_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='inventory_s_expiry__709598_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['quality_status'], name='inventory_s_quality_bd508f_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedgoods',
            index=models.Index(fields=['damage_type'], name='inventory_d_damage__a986aa_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedgoods',
            index=models.Index(fields=['is_approved'], name='inventory_d_is_appr_ea46e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountline',
            unique_together={('stock_count', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order_reference'], name='inventory_s_order_r_73141b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['status', 'expires_at'], name='inventory_s_status_c656ef_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type'], name='inventory_w_warehou_b51245_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['status'], name='inventory_b_status_5e8e51_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['order_reference'], name='inventory_b_order_r_b80ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousesection',
            index=models.Index(fields=['warehouse', 'zone'], name='inventory_w_warehou_28c4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousesection',
            index=models.Index(fields=['barcode'], name='inventory_w_barcode_f358ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousesection',
            unique_together={('warehouse', 'zone', 'aisle', 'rack', 'bin')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_5d230d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='inventory_s_created_2ec5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source'], name='inventory_s_source_bcb3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['status'], name='inventory_s_status_6486fa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['count_date'], name='inventory_s_count_d_27d5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_112b63_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['reorder_level'], name='inventory_s_reorder_1a0f87_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_movement'], name='inventory_s_last_mo_5b56ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_frozen'], name='inventory_s_is_froz_2c614d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'section'), name='unique_product_warehouse_section'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['serial_number'], name='inventory_s_serial__e6e8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['status'], name='inventory_s_status_4d8d9e_idx'),
        ),
    ]
