# Generated by Django 6.0.2 on 2026-02-23 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('warehouse_type', models.CharField(choices=[('main', 'Main Warehouse'), ('branch', 'Branch'), ('cold_storage', 'Cold Storage'), ('third_party', 'Third Party')], default='main', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Optional capacity in base units', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20)),
                ('aisle', models.CharField(max_length=20)),
                ('rack', models.CharField(max_length=20)),
                ('bin', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Warehouse Sections',
                'ordering': ['warehouse', 'zone', 'aisle', 'rack', 'bin'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10)),
                ('source', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sales Issue'), ('transfer', 'Warehouse Transfer'), ('adjustment', 'Manual Adjustment'), ('return', 'Return'), ('damage', 'Damage/Written Off'), ('count', 'Stock Count')], default='adjustment', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Reference document (PO, SO, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.warehousesection')),
            ],
            options={
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Number of base units per this unit', max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert when stock drops below this level', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.warehouse')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='inventory.warehousesection')),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousesection',
            index=models.Index(fields=['warehouse', 'zone'], name='inventory_w_warehou_28c4a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousesection',
            unique_together={('warehouse', 'zone', 'aisle', 'rack', 'bin')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_5d230d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='inventory_s_created_2ec5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source'], name='inventory_s_source_bcb3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_112b63_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['reorder_level'], name='inventory_s_reorder_1a0f87_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_updated'], name='inventory_s_last_up_75ebfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'section'), name='unique_product_warehouse_section'),
        ),
    ]
