# Generated by Django 6.0.2 on 2026-02-26 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0010_fix_critical_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='inventory_s_last_up_75ebfc_idx',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Prevent stock movements'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_counted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_movement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='max_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum desired stock level', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='safety_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Safety stock level', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='capacity_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_capacities', to='products.unit'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours in JSON format'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='temperature_zone',
            field=models.CharField(choices=[('ambient', 'Ambient (15-25°C)'), ('cool', 'Cool (8-15°C)'), ('cold', 'Cold (2-8°C)'), ('frozen', 'Frozen (-18 to -25°C)'), ('hazardous', 'Hazardous Materials')], default='ambient', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='utilization_threshold',
            field=models.DecimalField(decimal_places=2, default=85.0, help_text='Alert when utilization exceeds this percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='warehousesection',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warehousesection',
            name='current_occupancy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current occupancy in base units', max_digits=10),
        ),
        migrations.AddField(
            model_name='warehousesection',
            name='max_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum capacity for this section', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehousesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return'), ('DAMAGE', 'Damage/Written Off'), ('COUNT', 'Stock Count')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sales Issue'), ('transfer', 'Warehouse Transfer'), ('adjustment', 'Manual Adjustment'), ('return', 'Return'), ('damage', 'Damage/Written Off'), ('count', 'Stock Count'), ('production', 'Production'), ('assembly', 'Assembly')], default='adjustment', max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional capacity in base units', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'Main Warehouse'), ('branch', 'Branch'), ('cold_storage', 'Cold Storage'), ('third_party', 'Third Party'), ('dropship', 'Drop Shipping'), ('crossdock', 'Cross Dock')], default='main', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_movement'], name='inventory_s_last_mo_5b56ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_frozen'], name='inventory_s_is_froz_2c614d_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type'], name='inventory_w_warehou_b51245_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousesection',
            index=models.Index(fields=['barcode'], name='inventory_w_barcode_f358ce_idx'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='inventory.warehousesection'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='stock_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['status'], name='inventory_s_status_6486fa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['count_date'], name='inventory_s_count_d_27d5b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountline',
            unique_together={('stock_count', 'product')},
        ),
    ]
