# Generated by Django 6.0.2 on 2026-02-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockcount_stockcountline_and_more'),
        ('products', '0011_remove_batch_info_from_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Unique batch/lot number', max_length=50, unique=True)),
                ('manufacturing_date', models.DateField(blank=True, help_text='Date of manufacture', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date of expiry', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in this batch', max_digits=10)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Number of base units per this unit', max_digits=10)),
                ('received_date', models.DateField(auto_now_add=True, help_text='Date batch was received')),
                ('supplier', models.CharField(blank=True, help_text='Supplier/vendor name', max_length=100)),
                ('supplier_batch', models.CharField(blank=True, help_text="Supplier's batch number", max_length=50)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending Inspection'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quarantine', 'In Quarantine')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stock')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit')),
            ],
            options={
                'ordering': ['-expiry_date', 'batch_number'],
                'indexes': [models.Index(fields=['batch_number'], name='inventory_s_batch_n_3f0960_idx'), models.Index(fields=['expiry_date'], name='inventory_s_expiry__709598_idx'), models.Index(fields=['quality_status'], name='inventory_s_quality_bd508f_idx')],
            },
        ),
    ]
