# Generated by Django 6.0.2 on 2026-02-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity on hand in base units', max_digits=10),
        ),
    ]
