# Generated by Django 6.0.2 on 2026-02-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_quantity'),
        ('products', '0012_remove_product_stock_quantity_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_serial_tracking', models.BooleanField(default=False, help_text='Enable individual serial number tracking')),
                ('enable_batch_tracking', models.BooleanField(default=True, help_text='Enable batch/lot tracking with expiry dates')),
                ('enable_damaged_goods', models.BooleanField(default=False, help_text='Enable damaged goods recording')),
                ('enable_reservations', models.BooleanField(default=False, help_text='Enable stock reservations for sales orders')),
                ('enable_cycle_counting', models.BooleanField(default=False, help_text='Enable cycle counting workflow')),
                ('enable_auto_reorder', models.BooleanField(default=True, help_text='Enable automatic reorder alerts')),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average', 'Weighted Average'), ('standard', 'Standard Cost')], default='fifo', help_text='Default inventory valuation method', max_length=20)),
                ('reservation_expiry_hours', models.PositiveIntegerField(default=24, help_text='Hours after which unfulfilled reservations auto-release')),
                ('allow_backorders', models.BooleanField(default=False, help_text='Allow backorders when stock is insufficient')),
                ('require_writeoff_approval', models.BooleanField(default=True, help_text='Require manager approval for write-offs')),
                ('track_damage_reasons', models.BooleanField(default=True, help_text='Track reasons for damaged goods')),
                ('cycle_count_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('cycle_count_by', models.CharField(choices=[('section', 'By Section'), ('category', 'By Category'), ('value', 'By Value (ABC)')], default='section', max_length=20)),
                ('variance_threshold_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='Acceptable variance percentage before investigation', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Inventory Settings',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity reserved for sales orders', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='count_type',
            field=models.CharField(choices=[('full', 'Full Physical Inventory'), ('cycle', 'Cycle Count'), ('spot', 'Spot Check')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='cycle_category',
            field=models.CharField(blank=True, help_text='Category/section being cycle counted', max_length=50),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='variance_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='variance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='variance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_variances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('warranty', 'Under Warranty')], default='in_stock', max_length=20)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.stockbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='products.product')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousesection')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DamagedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_type', models.CharField(choices=[('shipping', 'Shipping Damage'), ('handling', 'Handling Damage'), ('storage', 'Storage Damage'), ('expired', 'Expired'), ('defective', 'Manufacturing Defect'), ('other', 'Other')], max_length=20)),
                ('disposition', models.CharField(choices=[('write_off', 'Write Off'), ('return_to_supplier', 'Return to Supplier'), ('sell_as_scrap', 'Sell as Scrap'), ('donate', 'Donate'), ('repair', 'Repair')], max_length=20)),
                ('description', models.TextField()),
                ('insurance_claim', models.BooleanField(default=False)),
                ('claim_number', models.CharField(blank=True, max_length=100)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_damages', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damaged_items', to='inventory.stockbatch')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damages', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_items', to='inventory.stock')),
                ('serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.serialnumber')),
            ],
            options={
                'verbose_name_plural': 'Damaged Goods',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_reference', models.CharField(help_text='Sales Order #', max_length=100)),
                ('order_line_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.stock')),
            ],
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('quantity_fulfilled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='inventory_b_status_5e8e51_idx'), models.Index(fields=['order_reference'], name='inventory_b_order_r_b80ab5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['serial_number'], name='inventory_s_serial__e6e8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='serialnumber',
            index=models.Index(fields=['status'], name='inventory_s_status_4d8d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedgoods',
            index=models.Index(fields=['damage_type'], name='inventory_d_damage__a986aa_idx'),
        ),
        migrations.AddIndex(
            model_name='damagedgoods',
            index=models.Index(fields=['is_approved'], name='inventory_d_is_appr_ea46e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order_reference'], name='inventory_s_order_r_73141b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['status', 'expires_at'], name='inventory_s_status_c656ef_idx'),
        ),
    ]
