# Generated by Django 6.0.2 on 2026-02-28 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('products.product', 'Products - Product'), ('products.unit', 'Products - Unit'), ('products.brand', 'Products - Brand'), ('products.productcategory', 'Products - Category'), ('products.pricelist', 'Products - Price List'), ('products.productattribute', 'Products - Product Attribute'), ('products.productattributevalue', 'Products - Attribute Value'), ('products.productvariant', 'Products - Product Variant'), ('products.productpricehistory', 'Products - Price History'), ('inventory.stock', 'Inventory - Stock'), ('inventory.stockbatch', 'Inventory - Stock Batch'), ('inventory.stockmovement', 'Inventory - Stock Movement'), ('inventory.warehouse', 'Inventory - Warehouse'), ('inventory.warehousesection', 'Inventory - Warehouse Section'), ('purchasing.purchaseorder', 'Purchasing - Purchase Order'), ('purchasing.vendor', 'Purchasing - Vendor'), ('purchasing.purchasereceipt', 'Purchasing - Purchase Receipt'), ('sales.customer', 'Sales - Customer'), ('sales.salesorder', 'Sales - Sales Order'), ('accounting.invoice', 'Accounting - Invoice'), ('accounting.bill', 'Accounting - Bill'), ('accounting.payment', 'Accounting - Payment'), ('accounting.journalentry', 'Accounting - Journal Entry')], help_text='The model this config applies to (app_label.model_name)', max_length=100, unique=True)),
                ('enabled_formats', models.JSONField(default=list, help_text='Enabled format strings, e.g. ["excel", "csv", "json"]')),
                ('default_format', models.CharField(choices=[('excel', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)'), ('pdf', 'PDF (.pdf)'), ('json', 'JSON (.json)'), ('ods', 'ODS (.ods)'), ('zip', 'ZIP Archive'), ('google_sheets', 'Google Sheets (coming soon)'), ('none', 'No Export')], default='excel', max_length=20)),
                ('include_headers_default', models.BooleanField(default=True)),
                ('include_footer_default', models.BooleanField(default=False)),
                ('compress_zip_default', models.BooleanField(default=False)),
                ('date_format_default', models.CharField(choices=[('%Y-%m-%d', 'YYYY-MM-DD (2025-01-31)'), ('%d/%m/%Y', 'DD/MM/YYYY (31/01/2025)'), ('%m/%d/%Y', 'MM/DD/YYYY (01/31/2025)'), ('%d-%m-%Y', 'DD-MM-YYYY (31-01-2025)'), ('%d %b %Y', 'DD Mon YYYY (31 Jan 2025)')], default='%Y-%m-%d', help_text='Python strftime format for dates in exports', max_length=30)),
                ('max_rows', models.PositiveIntegerField(default=10000, help_text='Maximum rows per export. 0 = unlimited.')),
                ('require_staff', models.BooleanField(default=True, help_text='If True, only staff users can export from this module')),
                ('is_active', models.BooleanField(default=True, help_text='If False, no export actions are shown for this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Export Configuration',
                'verbose_name_plural': 'Export Configurations',
                'ordering': ['module_key'],
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('export_format', models.CharField(max_length=20)),
                ('include_headers', models.BooleanField(default=True)),
                ('include_footer', models.BooleanField(default=False)),
                ('compressed', models.BooleanField(default=False)),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial (row limit hit)'), ('cancelled', 'Cancelled')], default='success', max_length=20)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Log',
                'verbose_name_plural': 'Export Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='exports_exp_user_id_447e99_idx'), models.Index(fields=['module_key', 'created_at'], name='exports_exp_module__edb5ec_idx'), models.Index(fields=['status', 'created_at'], name='exports_exp_status_5ac0f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserExportPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('products.product', 'Products - Product'), ('products.unit', 'Products - Unit'), ('products.brand', 'Products - Brand'), ('products.productcategory', 'Products - Category'), ('products.pricelist', 'Products - Price List'), ('products.productattribute', 'Products - Product Attribute'), ('products.productattributevalue', 'Products - Attribute Value'), ('products.productvariant', 'Products - Product Variant'), ('products.productpricehistory', 'Products - Price History'), ('inventory.stock', 'Inventory - Stock'), ('inventory.stockbatch', 'Inventory - Stock Batch'), ('inventory.stockmovement', 'Inventory - Stock Movement'), ('inventory.warehouse', 'Inventory - Warehouse'), ('inventory.warehousesection', 'Inventory - Warehouse Section'), ('purchasing.purchaseorder', 'Purchasing - Purchase Order'), ('purchasing.vendor', 'Purchasing - Vendor'), ('purchasing.purchasereceipt', 'Purchasing - Purchase Receipt'), ('sales.customer', 'Sales - Customer'), ('sales.salesorder', 'Sales - Sales Order'), ('accounting.invoice', 'Accounting - Invoice'), ('accounting.bill', 'Accounting - Bill'), ('accounting.payment', 'Accounting - Payment'), ('accounting.journalentry', 'Accounting - Journal Entry')], max_length=100)),
                ('preferred_format', models.CharField(choices=[('excel', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)'), ('pdf', 'PDF (.pdf)'), ('json', 'JSON (.json)'), ('ods', 'ODS (.ods)'), ('zip', 'ZIP Archive'), ('google_sheets', 'Google Sheets (coming soon)'), ('none', 'No Export')], default='excel', max_length=20)),
                ('include_headers', models.BooleanField(default=True)),
                ('include_footer', models.BooleanField(default=False)),
                ('compress_zip', models.BooleanField(default=False)),
                ('date_format', models.CharField(choices=[('%Y-%m-%d', 'YYYY-MM-DD (2025-01-31)'), ('%d/%m/%Y', 'DD/MM/YYYY (31/01/2025)'), ('%m/%d/%Y', 'MM/DD/YYYY (01/31/2025)'), ('%d-%m-%Y', 'DD-MM-YYYY (31-01-2025)'), ('%d %b %Y', 'DD Mon YYYY (31 Jan 2025)')], default='%Y-%m-%d', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Export Preference',
                'verbose_name_plural': 'User Export Preferences',
                'ordering': ['user', 'module_key'],
                'unique_together': {('user', 'module_key')},
            },
        ),
    ]
