# Generated by Django 6.0.2 on 2026-02-23 09:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor (optional)', max_length=255, verbose_name='Address Line 2')),
                ('postal_code', models.CharField(help_text='ZIP or postal code', max_length=20, verbose_name='ZIP / Postal Code')),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('credit_days', models.PositiveIntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_cities', to='core.city', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_countries', to='core.country', verbose_name='Country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_regions', to='core.region', verbose_name='Region / State')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=50, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partial', 'Partially Received'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.vendor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity already received into stock', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('section', models.ForeignKey(blank=True, help_text='Optional: receive into specific bin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousesection')),
                ('unit', models.ForeignKey(blank=True, help_text='Unit in which this product is ordered. Leave blank for base unit.', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Optional: override order warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'product'], name='purchasing__order_i_ed6163_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['code'], name='purchasing__code_8448fd_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['email'], name='purchasing__email_e1fc32_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='purchasing__is_acti_040a9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_vendor_code_case_insensitive'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchasing__status_04b4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor', 'order_date'], name='purchasing__vendor__bccc11_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchasing__po_numb_f09ba8_idx'),
        ),
    ]
