# Generated by Django 6.0.2 on 2026-02-27 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0005_inventorysettings_stock_reserved_quantity_and_more'),
        ('products', '0013_add_currency_to_product'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('status_change', 'Status Changed'), ('approve', 'Approved'), ('cancel', 'Cancelled'), ('receive', 'Received')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Purchase Order Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_note_number', models.CharField(blank=True, help_text="Vendor's delivery note number", max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_accepted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quality_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('quarantine', 'Quarantine'), ('partial', 'Partial Accept')], default='accepted', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_multi_currency', models.BooleanField(default=False)),
                ('enable_purchase_approval', models.BooleanField(default=False)),
                ('enable_batch_tracking', models.BooleanField(default=True)),
                ('enable_quality_check', models.BooleanField(default=False)),
                ('enable_partial_receiving', models.BooleanField(default=True)),
                ('enable_auto_po_number', models.BooleanField(default=True)),
                ('enable_vendor_credit_notes', models.BooleanField(default=False)),
                ('enable_purchase_returns', models.BooleanField(default=False)),
                ('enable_receipt_batching', models.BooleanField(default=False)),
                ('approval_levels', models.PositiveSmallIntegerField(default=1, help_text='Number of approval levels required')),
                ('require_approval_above', models.DecimalField(decimal_places=2, default=0, help_text='Require approval for orders above this amount', max_digits=12)),
                ('default_payment_terms', models.CharField(choices=[('immediate', 'Immediate'), ('net15', 'Net 15'), ('net30', 'Net 30'), ('net45', 'Net 45'), ('net60', 'Net 60')], default='net30', max_length=20)),
                ('po_prefix', models.CharField(default='PO-', max_length=10)),
                ('po_next_number', models.PositiveIntegerField(default=1)),
                ('po_number_padding', models.PositiveIntegerField(default=4, help_text='Number of digits for PO number')),
                ('notify_on_overdue', models.BooleanField(default=True)),
                ('notify_days_before', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchasing Settings',
                'verbose_name_plural': 'Purchasing Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date', '-id'], 'permissions': [('can_approve_purchase_orders', 'Can approve purchase orders'), ('can_cancel_purchase_orders', 'Can cancel purchase orders')]},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='purchasing__is_acti_040a9b_idx',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('net15', 'Net 15'), ('net30', 'Net 30'), ('net45', 'Net 45'), ('net60', 'Net 60'), ('cod', 'Cash on Delivery')], default='net30', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Leave blank to use vendor address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_reference',
            field=models.CharField(blank=True, help_text="Vendor's PO number", max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='average_delivery_days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Mark as preferred vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('net15', 'Net 15'), ('net30', 'Net 30'), ('net45', 'Net 45'), ('net60', 'Net 60')], default='net30', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='quality_rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, help_text='Vendor website URL'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('partial', 'Partially Received'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='credit_days',
            field=models.PositiveIntegerField(default=0, help_text='Credit days allowed'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Registration Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tax ID/VAT Number'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_date'], name='purchasing__expecte_25fb06_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='purchasing__created_2e8e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active', 'is_preferred'], name='purchasing__is_acti_504e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='purchasing__name_6dc288_idx'),
        ),
        migrations.AddField(
            model_name='purchaseorderhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderhistory',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipt_lines', to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousesection'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasingsettings',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasingsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['receipt_number'], name='purchasing__receipt_502aed_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['purchase_order', 'status'], name='purchasing__purchas_38454f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['received_date'], name='purchasing__receive_78bd93_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['receipt', 'product'], name='purchasing__receipt_3c2791_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['batch_number'], name='purchasing__batch_n_de0a3d_idx'),
        ),
    ]
