# Generated by Django 6.0.2 on 2026-02-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseorderhistory_purchasereceipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
