# Generated by Django 6.0.2 on 2026-03-03 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority. Used when resolving conflicts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('warehouses', models.ManyToManyField(blank=True, related_name='branches', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='rbac.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('products.product', 'Products - Product'), ('products.unit', 'Products - Unit'), ('products.brand', 'Products - Brand'), ('products.productcategory', 'Products - Category'), ('products.pricelist', 'Products - Price List'), ('products.productattribute', 'Products - Product Attribute'), ('products.productattributevalue', 'Products - Attribute Value'), ('products.productvariant', 'Products - Product Variant'), ('products.productpricehistory', 'Products - Price History'), ('inventory.stock', 'Inventory - Stock'), ('inventory.stockbatch', 'Inventory - Stock Batch'), ('inventory.stockmovement', 'Inventory - Stock Movement'), ('inventory.warehouse', 'Inventory - Warehouse'), ('inventory.warehousesection', 'Inventory - Warehouse Section'), ('purchasing.purchaseorder', 'Purchasing - Purchase Order'), ('purchasing.vendor', 'Purchasing - Vendor'), ('purchasing.purchasereceipt', 'Purchasing - Purchase Receipt'), ('sales.customer', 'Sales - Customer'), ('sales.salesorder', 'Sales - Sales Order'), ('accounting.invoice', 'Accounting - Invoice'), ('accounting.bill', 'Accounting - Bill'), ('accounting.payment', 'Accounting - Payment'), ('accounting.journalentry', 'Accounting - Journal Entry')], max_length=100)),
                ('action', models.CharField(help_text='e.g. confirm, approve, post, cancel', max_length=50)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Rule only applies when the document amount is >= this value. Leave blank to always apply.', max_digits=18, null=True)),
                ('required_approval_level', models.PositiveIntegerField(default=1, help_text='Minimum UserProfile.approval_level needed to perform this action.')),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Step order in multi-level approval (1=first).')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('required_role', models.ForeignKey(blank=True, help_text='If set, user must also have this role (in addition to approval_level).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.role')),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
                'ordering': ['module', 'action', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.PositiveIntegerField(default=0, help_text='0=no approval rights, 1-5=approval authority level.')),
                ('work_start', models.TimeField(blank=True, help_text='Start of allowed work hours (local time). Leave blank for no restriction.', null=True)),
                ('work_end', models.TimeField(blank=True, help_text='End of allowed work hours (local time). Leave blank for no restriction.', null=True)),
                ('work_days', models.JSONField(default=list, help_text='Allowed weekdays as list of integers (0=Mon … 6=Sun). Empty = all days.')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rbac.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='rbac.department')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rbac.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('warehouses', models.ManyToManyField(blank=True, help_text='Warehouses this user can access. Empty = no warehouse restriction.', related_name='assigned_users', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('approve', 'Approve'), ('reject', 'Reject'), ('print', 'Print'), ('view', 'View'), ('lock', 'Account Locked')], db_index=True, max_length=20)),
                ('module', models.CharField(blank=True, db_index=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='rbac_auditl_user_id_06e66a_idx'), models.Index(fields=['module', 'timestamp'], name='rbac_auditl_module_d74fee_idx'), models.Index(fields=['action', 'timestamp'], name='rbac_auditl_action_a3cc4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('products.product', 'Products - Product'), ('products.unit', 'Products - Unit'), ('products.brand', 'Products - Brand'), ('products.productcategory', 'Products - Category'), ('products.pricelist', 'Products - Price List'), ('products.productattribute', 'Products - Product Attribute'), ('products.productattributevalue', 'Products - Attribute Value'), ('products.productvariant', 'Products - Product Variant'), ('products.productpricehistory', 'Products - Price History'), ('inventory.stock', 'Inventory - Stock'), ('inventory.stockbatch', 'Inventory - Stock Batch'), ('inventory.stockmovement', 'Inventory - Stock Movement'), ('inventory.warehouse', 'Inventory - Warehouse'), ('inventory.warehousesection', 'Inventory - Warehouse Section'), ('purchasing.purchaseorder', 'Purchasing - Purchase Order'), ('purchasing.vendor', 'Purchasing - Vendor'), ('purchasing.purchasereceipt', 'Purchasing - Purchase Receipt'), ('sales.customer', 'Sales - Customer'), ('sales.salesorder', 'Sales - Sales Order'), ('accounting.invoice', 'Accounting - Invoice'), ('accounting.bill', 'Accounting - Bill'), ('accounting.payment', 'Accounting - Payment'), ('accounting.journalentry', 'Accounting - Journal Entry')], max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('allowed_export_formats', models.JSONField(default=list, help_text='Allowed export formats for this role+module. Empty = all enabled formats.')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'ordering': ['module'],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('products.product', 'Products - Product'), ('products.unit', 'Products - Unit'), ('products.brand', 'Products - Brand'), ('products.productcategory', 'Products - Category'), ('products.pricelist', 'Products - Price List'), ('products.productattribute', 'Products - Product Attribute'), ('products.productattributevalue', 'Products - Attribute Value'), ('products.productvariant', 'Products - Product Variant'), ('products.productpricehistory', 'Products - Price History'), ('inventory.stock', 'Inventory - Stock'), ('inventory.stockbatch', 'Inventory - Stock Batch'), ('inventory.stockmovement', 'Inventory - Stock Movement'), ('inventory.warehouse', 'Inventory - Warehouse'), ('inventory.warehousesection', 'Inventory - Warehouse Section'), ('purchasing.purchaseorder', 'Purchasing - Purchase Order'), ('purchasing.vendor', 'Purchasing - Vendor'), ('purchasing.purchasereceipt', 'Purchasing - Purchase Receipt'), ('sales.customer', 'Sales - Customer'), ('sales.salesorder', 'Sales - Sales Order'), ('accounting.invoice', 'Accounting - Invoice'), ('accounting.bill', 'Accounting - Bill'), ('accounting.payment', 'Accounting - Payment'), ('accounting.journalentry', 'Accounting - Journal Entry')], max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Field Permission',
                'verbose_name_plural': 'Field Permissions',
                'ordering': ['module', 'field_name'],
                'unique_together': {('role', 'module', 'field_name')},
            },
        ),
    ]
