# Generated by Django 6.0.2 on 2026-02-28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings  # Add this import


def create_default_accounts(apps, schema_editor):
    """Create standard chart of accounts"""
    Account = apps.get_model('accounting', 'Account')
    
    accounts = [
        # Assets (1000-1999)
        ('1000', 'Cash', 'asset', True, 'USD'),
        ('1010', 'Accounts Receivable', 'asset', True, 'USD'),
        ('1020', 'Inventory', 'asset', True, 'USD'),
        ('1030', 'Prepaid Expenses', 'asset', True, 'USD'),
        ('1040', 'Fixed Assets', 'asset', True, 'USD'),
        ('1050', 'Accumulated Depreciation', 'asset', True, 'USD'),
        
        # Liabilities (2000-2999)
        ('2000', 'Accounts Payable', 'liability', True, 'USD'),
        ('2010', 'Sales Tax Payable', 'liability', True, 'USD'),
        ('2020', 'Accrued Liabilities', 'liability', True, 'USD'),
        ('2030', 'Notes Payable', 'liability', True, 'USD'),
        
        # Equity (3000-3999)
        ('3000', "Owner's Equity", 'equity', True, 'USD'),
        ('3010', 'Retained Earnings', 'equity', True, 'USD'),
        ('3020', 'Drawings', 'equity', True, 'USD'),
        
        # Income (4000-4999)
        ('4000', 'Sales Revenue', 'income', True, 'USD'),
        ('4010', 'Service Revenue', 'income', True, 'USD'),
        ('4020', 'Interest Income', 'income', True, 'USD'),
        ('4030', 'Discounts Given', 'income', True, 'USD'),
        
        # Expenses (5000-5999)
        ('5000', 'Cost of Goods Sold', 'expense', True, 'USD'),
        ('5010', 'Salaries Expense', 'expense', True, 'USD'),
        ('5020', 'Rent Expense', 'expense', True, 'USD'),
        ('5030', 'Utilities Expense', 'expense', True, 'USD'),
        ('5040', 'Office Supplies', 'expense', True, 'USD'),
        ('5050', 'Depreciation Expense', 'expense', True, 'USD'),
        ('5060', 'Purchases', 'expense', True, 'USD'),
        ('5070', 'Shipping Expense', 'expense', True, 'USD'),
        ('5080', 'Bank Charges', 'expense', True, 'USD'),
    ]
    
    for code, name, type, is_system, currency in accounts:
        Account.objects.create(
            code=code,
            name=name,
            type=type,
            is_system=is_system,
            is_active=True,
            currency=currency,
            opening_balance=0
        )


def create_default_fiscal_year(apps, schema_editor):
    """Create current fiscal year"""
    FiscalYear = apps.get_model('accounting', 'FiscalYear')
    FiscalPeriod = apps.get_model('accounting', 'FiscalPeriod')
    from django.utils import timezone
    from datetime import timedelta
    
    today = timezone.now().date()
    start_date = today.replace(month=1, day=1)
    end_date = today.replace(month=12, day=31)
    
    fiscal_year = FiscalYear.objects.create(
        name=f"FY {today.year}",
        start_date=start_date,
        end_date=end_date
    )
    
    # Create monthly periods
    for month in range(1, 13):
        month_start = start_date.replace(month=month, day=1)
        if month == 12:
            month_end = end_date
        else:
            month_end = start_date.replace(month=month+1, day=1) - timedelta(days=1)
        
        FiscalPeriod.objects.create(
            fiscal_year=fiscal_year,
            period_number=month,
            period_type='monthly',
            start_date=month_start,
            end_date=month_end
        )


def create_accounting_settings(apps, schema_editor):
    """Create default accounting settings"""
    AccountingSettings = apps.get_model('accounting', 'AccountingSettings')
    Account = apps.get_model('accounting', 'Account')
    
    # Get default accounts
    try:
        cash_account = Account.objects.get(code='1000')
        ar_account = Account.objects.get(code='1010')
        ap_account = Account.objects.get(code='2000')
        inventory_account = Account.objects.get(code='1020')
        sales_account = Account.objects.get(code='4000')
        purchase_account = Account.objects.get(code='5060')
        tax_account = Account.objects.get(code='2010')
        cogs_account = Account.objects.get(code='5000')
        shipping_account = Account.objects.get(code='5070')
        discount_account = Account.objects.get(code='4030')
    except Account.DoesNotExist:
        # If accounts don't exist yet, skip - they'll need to be set manually
        return
    
    AccountingSettings.objects.create(
        default_cash_account=cash_account,
        default_ar_account=ar_account,
        default_ap_account=ap_account,
        default_inventory_account=inventory_account,
        default_sales_account=sales_account,
        default_purchase_account=purchase_account,
        default_tax_account=tax_account,
        default_cogs_account=cogs_account,
        default_shipping_account=shipping_account,
        default_discount_account=discount_account,
        tax_system='none',
        enable_multi_currency=False,
        enable_approval_workflow=False,
        journal_entry_prefix='JE-',
        journal_entry_padding=5,
        journal_entry_next_number=1
    )


class Migration(migrations.Migration):
    """
    Add Chart of Accounts and related models
    This migration can be rolled back
    """
    
    dependencies = [
        ('accounting', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Create FiscalYear model
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        
        # Create FiscalPeriod model
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ['fiscal_year', 'period_number'],
                'unique_together': {('fiscal_year', 'period_number')},
            },
        ),
        
        # Create Account model
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System account - cannot be deleted')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_routing_number', models.CharField(blank=True, max_length=50)),
                ('bank_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        
        # Create ExchangeRate model
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        
        # Create AccountingSettings model
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_system', models.CharField(choices=[('none', 'No Tax'), ('sales_tax', 'Sales Tax'), ('vat', 'Value Added Tax (VAT)'), ('gst', 'Goods & Services Tax (GST)')], default='none', max_length=20)),
                ('tax_inclusive_pricing', models.BooleanField(default=False)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fiscal_year_start_month', models.PositiveIntegerField(default=1, help_text='Month fiscal year starts (1-12)')),
                ('fiscal_year_start_day', models.PositiveIntegerField(default=1, help_text='Day fiscal year starts (1-31)')),
                ('journal_entry_prefix', models.CharField(default='JE-', max_length=10)),
                ('journal_entry_padding', models.PositiveIntegerField(default=5)),
                ('journal_entry_next_number', models.PositiveIntegerField(default=1)),
                ('enable_multi_currency', models.BooleanField(default=False)),
                ('enable_approval_workflow', models.BooleanField(default=False)),
                ('enable_audit_trail', models.BooleanField(default=True)),
                ('enable_budgeting', models.BooleanField(default=False)),
                ('date_format', models.CharField(choices=[('%Y-%m-%d', 'YYYY-MM-DD'), ('%d-%m-%Y', 'DD-MM-YYYY'), ('%m-%d-%Y', 'MM-DD-YYYY')], default='%Y-%m-%d', max_length=20)),
                ('show_running_balance', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_ar_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_ap_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_discount_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_purchase_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_sales_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_shipping_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('default_tax_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Settings',
                'verbose_name_plural': 'Accounting Settings',
            },
        ),
        
        # Create AuditLog model
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('POST', 'Post'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VOID', 'Void'), ('RECONCILE', 'Reconcile')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        
        # Add new fields to JournalEntry
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        
        # Add new fields to JournalLine
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalline',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='journalline',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='journalline',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='journalline',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalline',
            name='reconciled_date',
            field=models.DateField(blank=True, null=True),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting_a_code_0a11c2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type'], name='accounting_a_type_f7a4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting_a_is_act_46325e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='accounting_a_content_7b6d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='accounting_a_user_id_20ecf0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='accounting_a_action_f8aac7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='accounting_a_timesta_60d5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['approval_status'], name='accounting_j_approva_a7cfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted'], name='accounting_j_is_post_aa120a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'journal_entry'], name='accounting_j_account_b5ebaf_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['debit_credit'], name='accounting_j_debit_c_c8a695_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['is_reconciled'], name='accounting_j_is_reco_7f31c8_idx'),
        ),
        
        # Run data migrations
        migrations.RunPython(create_default_accounts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_default_fiscal_year, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_accounting_settings, reverse_code=migrations.RunPython.noop),
    ]