# Generated by Django 6.0.2 on 2026-02-28 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_chart_of_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__code_c93a8f_idx',
            old_name='accounting_a_code_0a11c2_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__type_01d50f_idx',
            old_name='accounting_a_type_f7a4ab_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__is_acti_28dd04_idx',
            old_name='accounting_a_is_act_46325e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounting__content_1e8bb2_idx',
            old_name='accounting_a_content_7b6d8a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounting__user_id_2b0b23_idx',
            old_name='accounting_a_user_id_20ecf0_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounting__action_d90ab6_idx',
            old_name='accounting_a_action_f8aac7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounting__timesta_2c735b_idx',
            old_name='accounting_a_timesta_60d5b4_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__approva_a968b7_idx',
            old_name='accounting_j_approva_a7cfb2_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__is_post_95b69a_idx',
            old_name='accounting_j_is_post_aa120a_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='accounting__account_d5c63f_idx',
            old_name='accounting_j_account_b5ebaf_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='accounting__debit_c_1ea970_idx',
            old_name='accounting_j_debit_c_c8a695_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='accounting__is_reco_913d49_idx',
            old_name='accounting_j_is_reco_7f31c8_idx',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='source_content_type',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='source_object_id',
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='enable_auto_posting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_ap_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_ar_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_cash_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_cogs_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_discount_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_inventory_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_purchase_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_sales_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_shipping_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_tax_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='period_number',
            field=models.PositiveIntegerField(help_text='1-12 for monthly, 1-4 for quarterly'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('sale', 'Sales Journal'), ('purchase', 'Purchases Journal'), ('cash_receipt', 'Cash Receipts Journal'), ('cash_payment', 'Cash Payments Journal'), ('general', 'General Journal')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_number'], name='accounting__entry_n_734b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['journal_type'], name='accounting__journal_bd8845_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_date'], name='accounting__entry_d_79c286_idx'),
        ),
    ]
