# Generated by Django 6.0.2 on 2026-02-23 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('individual', 'Individual Consumer'), ('business', 'Business / Trader')], default='individual', max_length=20, verbose_name='Customer Type')),
                ('first_name', models.CharField(blank=True, help_text='Required for individual customers', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Required for individual customers', max_length=100, verbose_name='Last Name')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('company_name', models.CharField(blank=True, help_text='Required for business customers', max_length=255, verbose_name='Company Name')),
                ('company_registration', models.CharField(blank=True, max_length=50, verbose_name='Company Registration Number')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Tax / VAT Number')),
                ('business_type', models.CharField(blank=True, help_text='e.g., Retailer, Wholesaler, Distributor', max_length=100, verbose_name='Business Type')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile Number')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax Number')),
                ('billing_address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('billing_address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('billing_postal_code', models.CharField(max_length=20, verbose_name='ZIP / Postal Code')),
                ('same_as_billing', models.BooleanField(default=False, help_text='If checked, shipping address will copy billing address automatically.', verbose_name='Same as Billing')),
                ('shipping_address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP / Postal Code')),
                ('payment_type', models.CharField(choices=[('pay_now', 'Pay Now'), ('credit', 'Credit')], default='pay_now', max_length=20, verbose_name='Payment Type')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit')),
                ('credit_days', models.PositiveIntegerField(default=0, help_text='Number of days allowed for payment', verbose_name='Credit Days')),
                ('customer_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Customer Code')),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('INR', 'Indian Rupee'), ('PKR', 'Pakistani Rupee')], default='USD', max_length=5, verbose_name='Default Currency')),
                ('price_list', models.CharField(blank=True, help_text='e.g., Retail, Wholesale, Distributor', max_length=50, verbose_name='Price List')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Default Discount %')),
                ('preferred_language', models.CharField(blank=True, max_length=10, verbose_name='Preferred Language')),
                ('source', models.CharField(blank=True, help_text='e.g., Website, Referral, Walk-in', max_length=100, verbose_name='Lead Source')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP Customer')),
                ('position', models.IntegerField(default=0, verbose_name='Display Position')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Loyalty Points')),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50, verbose_name='Preferred Payment Method')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Order Date')),
                ('total_orders_count', models.IntegerField(default=0, verbose_name='Total Orders Count')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Average Order Value')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Salesperson')),
                ('billing_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_billing_cities', to='core.city', verbose_name='City')),
                ('billing_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_billing_countries', to='core.country', verbose_name='Country')),
                ('billing_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_billing_regions', to='core.region', verbose_name='Region / State')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('shipping_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_shipping_cities', to='core.city', verbose_name='City')),
                ('shipping_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_shipping_countries', to='core.country', verbose_name='Country')),
                ('shipping_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_shipping_regions', to='core.region', verbose_name='Region / State')),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['position', 'full_name', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='sales.customer')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online Payment')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesinvoice')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=50, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partial', 'Partially Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('invoiced', 'Invoiced')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='sales.customer')),
                ('warehouse', models.ForeignKey(help_text='Default warehouse for this order', on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice', to='sales.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('section', models.ForeignKey(blank=True, help_text='Specific bin/section to pick from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousesection')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Override default warehouse for this line', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='sales_custo_email_b3bee2_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='sales_custo_custome_c546c5_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='sales_custo_custome_890109_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='sales_custo_is_acti_1b1d19_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='sales_custo_company_a82986_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='sales_sales_status_480214_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_date'], name='sales_sales_order_d_55e46c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', 'order_date'], name='sales_sales_custome_23226b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status'], name='sales_sales_status_826768_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['due_date'], name='sales_sales_due_dat_9b6c48_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', 'invoice_date'], name='sales_sales_custome_0d19f7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['order', 'product'], name='sales_sales_order_i_44dd8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderline',
            unique_together={('order', 'product')},
        ),
    ]
