# Generated by Django 6.0.2 on 2026-02-25 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pricelist_product_base_price_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom discount percentage (overrides price list)', max_digits=5, null=True, verbose_name='Custom Discount %'),
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_price_list',
            field=models.ForeignKey(blank=True, help_text='Override the default pricing tier with a specific price list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pricelist', verbose_name='Custom Price List'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pricing_tier',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('distributor', 'Distributor'), ('special', 'Special')], default='retail', help_text='Determines which price list applies to this customer', max_length=20, verbose_name='Pricing Tier'),
        ),
    ]
