# Generated by Django 6.0.2 on 2026-02-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_custom_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_invoicing', models.BooleanField(default=True, help_text='Auto-create invoice when order is confirmed')),
                ('enable_backorders', models.BooleanField(default=False, help_text='Allow backorders when stock is insufficient')),
                ('enable_customer_credit_check', models.BooleanField(default=True, help_text='Check credit limit before confirming orders')),
                ('default_payment_terms', models.CharField(default='Net 30', help_text='Default payment terms', max_length=50)),
                ('invoice_prefix', models.CharField(default='INV-', help_text='Prefix for invoice numbers', max_length=10)),
                ('order_prefix', models.CharField(default='SO-', help_text='Prefix for sales order numbers', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Sales Settings',
            },
        ),
    ]
