# Generated by Django 6.0.2 on 2026-02-26 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_approval_notes_salesorder_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salessettings',
            options={'verbose_name': 'Sales Settings', 'verbose_name_plural': 'Sales Settings'},
        ),
        migrations.RemoveField(
            model_name='salessettings',
            name='default_payment_terms',
        ),
        migrations.RemoveField(
            model_name='salessettings',
            name='enable_auto_invoicing',
        ),
        migrations.RemoveField(
            model_name='salessettings',
            name='enable_customer_credit_check',
        ),
        migrations.AddField(
            model_name='salessettings',
            name='auto_confirm_approved_orders',
            field=models.BooleanField(default=True, help_text='Automatically confirm orders after approval', verbose_name='Auto-confirm Approved Orders'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salessettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax rate percentage', max_digits=5, verbose_name='Default Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='delivery_note_prefix',
            field=models.CharField(default='DN-', help_text='Prefix for delivery notes', max_length=10, verbose_name='Delivery Note Prefix'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_credit_limit',
            field=models.BooleanField(default=True, help_text='Enforce customer credit limits', verbose_name='Enable Credit Limit'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_delivery_notes',
            field=models.BooleanField(default=False, help_text='Generate delivery notes', verbose_name='Enable Delivery Notes'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_discounts',
            field=models.BooleanField(default=True, help_text='Enable discount management', verbose_name='Enable Discounts'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_invoicing',
            field=models.BooleanField(default=True, help_text='Enable invoice generation', verbose_name='Enable Invoicing'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_order_approval',
            field=models.BooleanField(default=False, help_text='Require approval for sales orders', verbose_name='Enable Order Approval'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_profit_tracking',
            field=models.BooleanField(default=False, help_text='Track profit margins', verbose_name='Enable Profit Tracking'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_quotations',
            field=models.BooleanField(default=True, help_text='Enable quotation management', verbose_name='Enable Quotations'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_sales_orders',
            field=models.BooleanField(default=True, help_text='Enable sales orders', verbose_name='Enable Sales Orders'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_sales_returns',
            field=models.BooleanField(default=False, help_text='Handle sales returns/RMA', verbose_name='Enable Sales Returns'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='enable_tax_calculation',
            field=models.BooleanField(default=True, help_text='Enable tax calculation', verbose_name='Enable Tax Calculation'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='quotation_prefix',
            field=models.CharField(default='Q-', help_text='Prefix for quotation numbers', max_length=10, verbose_name='Quotation Prefix'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='quotation_valid_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days quotations are valid', verbose_name='Quotation Validity (Days)'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='require_approval_for_amount',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Orders above this amount require approval', max_digits=12, verbose_name='Approval Threshold'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='return_prefix',
            field=models.CharField(default='RMA-', help_text='Prefix for return numbers', max_length=10, verbose_name='Return Prefix'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='enable_backorders',
            field=models.BooleanField(default=False, help_text='Allow backorders when stock insufficient', verbose_name='Enable Backorders'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='invoice_prefix',
            field=models.CharField(default='INV-', help_text='Prefix for invoice numbers', max_length=10, verbose_name='Invoice Prefix'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='order_prefix',
            field=models.CharField(default='SO-', help_text='Prefix for sales order numbers', max_length=10, verbose_name='Order Prefix'),
        ),
    ]
