# Generated by Django 6.0.2 on 2026-03-03 20:09

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Retail Price, Wholesale Price', max_length=100)),
                ('code', models.CharField(help_text='e.g., RETAIL, WHOLESALE', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower number = higher priority')),
                ('discount_method', models.CharField(choices=[('fixed', 'Fixed Price'), ('percentage', 'Percentage off base'), ('formula', 'Formula based')], default='fixed', max_length=20)),
                ('default_discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Default discount % for this price list', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default price list for new products')),
                ('applicable_to_retail', models.BooleanField(default=True)),
                ('applicable_to_wholesale', models.BooleanField(default=False)),
                ('applicable_to_distributor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_br_is_acti_e09143_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., iPhone 15 Pro', max_length=100)),
                ('code', models.CharField(help_text='e.g., A3102', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specs in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.brand')),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('model_name', models.CharField(blank=True, help_text='Display model name (can be auto-filled from model_number)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_type', models.CharField(choices=[('ST', 'Stockable'), ('CO', 'Consumable'), ('SE', 'Service')], default='ST', max_length=2)),
                ('is_featured', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='e.g., 10x5x2 cm', max_length=50)),
                ('multi_pack', models.IntegerField(default=1, help_text='e.g., 6-pack')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Base price for calculations', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Product brand/manufacturer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand')),
                ('currency', models.ForeignKey(blank=True, help_text='Currency for base price', null=True, on_delete=django.db.models.deletion.PROTECT, to='config_settings.currency')),
                ('default_price_list', models.ForeignKey(blank=True, help_text='Default price list for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_products', to='products.pricelist')),
                ('model_number', models.ForeignKey(blank=True, help_text='Specific model number', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.modelnumber')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('code', models.SlugField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productattribute')),
            ],
            options={
                'ordering': ['attribute', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='products.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('default_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('notes', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this product in this price list', max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override the default discount % for this product', max_digits=5, null=True)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity to get this price')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('exchange_rate_at_creation', models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate when this price was set', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, help_text='Currency for this price (defaults to product currency)', null=True, on_delete=django.db.models.deletion.PROTECT, to='config_settings.currency')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_prices', to='products.product')),
            ],
            options={
                'ordering': ['product', 'price_list__priority', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('attributes', models.JSONField(default=dict, help_text='Store variant attributes like size, color')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('unit_type', models.CharField(choices=[('weight', 'Weight (Mass)'), ('volume', 'Volume (Capacity)'), ('length', 'Length (Distance)'), ('area', 'Area (Surface Size)'), ('standard', 'Standard (Discrete)'), ('packaging', 'Primary Packaging'), ('time', 'Duration / Time'), ('digital', 'Digital Storage'), ('energy', 'Energy')], default='standard', help_text='Type of unit (Weight, Volume, Length, etc.)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['unit_type', 'name'],
                'indexes': [models.Index(fields=['code'], name='products_un_code_d8ae0d_idx'), models.Index(fields=['unit_type', 'is_active'], name='products_un_unit_ty_3fdeb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='How many base units inside this packing (e.g. 20 PCS)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional special price for this packing', max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='products.product')),
                ('packing_unit', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='packing_units', to='products.unit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='Base unit for inventory tracking (e.g., PCS, KG)', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='products.unit'),
        ),
        migrations.AddIndex(
            model_name='modelnumber',
            index=models.Index(fields=['code'], name='products_mo_code_680fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='modelnumber',
            index=models.Index(fields=['brand', 'is_active'], name='products_mo_brand_i_b37838_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelnumber',
            unique_together={('brand', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('attribute', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributeassignment',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug'], name='products_pr_slug_f060a9_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['code'], name='products_pr_code_dbab3f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['active', 'is_featured'], name='products_pr_active_d20bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['tree_id', 'lft'], name='products_productcategory_t1988'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'price_list'], name='products_pr_product_c0a594_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['price_list', 'min_quantity'], name='products_pr_price_l_8fdcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['currency'], name='products_pr_currenc_fb7faf_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'currency'], name='products_pr_product_63a48b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'price_list', 'min_quantity')},
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['product', '-changed_at'], name='products_pr_product_40293a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='products_pr_sku_dcab68_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku')},
        ),
        migrations.AddIndex(
            model_name='productpacking',
            index=models.Index(fields=['product', 'is_default'], name='products_pr_product_352392_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productpacking',
            unique_together={('product', 'packing_unit', 'quantity')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'is_featured'], name='products_pr_active_b1327f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'active'], name='products_pr_categor_24b98b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'active'], name='products_pr_brand_i_514cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_number'], name='products_pr_model_n_bf8639_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_unit'], name='products_pr_base_un_ef888d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', 'active'], name='products_pr_created_839b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['currency'], name='products_pr_currenc_92522f_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='cost_positive'),
        ),
    ]
