# Generated by Django 6.0.2 on 2026-02-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productattribute_productattributeassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, help_text='Display model name (can be auto-filled from model_number)', max_length=100),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_br_is_acti_e09143_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Product brand/manufacturer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand'),
        ),
        migrations.CreateModel(
            name='ModelNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., iPhone 15 Pro', max_length=100)),
                ('code', models.CharField(help_text='e.g., A3102', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specs in JSON format')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.brand')),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.ForeignKey(blank=True, help_text='Specific model number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.modelnumber'),
        ),
        migrations.AddIndex(
            model_name='modelnumber',
            index=models.Index(fields=['code'], name='products_mo_code_680fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='modelnumber',
            index=models.Index(fields=['brand', 'is_active'], name='products_mo_brand_i_b37838_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelnumber',
            unique_together={('brand', 'code')},
        ),
    ]
