# Generated by Django 6.0.2 on 2026-02-24 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_model_name_brand_product_brand_modelnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='Base unit for inventory tracking (e.g., PCS, KG)', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_products', to='products.unit'),
        ),
        migrations.AlterField(
            model_name='productpacking',
            name='packing_unit',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='packing_units', to='products.unit'),
        ),
    ]
