# Generated by Django 6.0.2 on 2026-02-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_base_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Weight, Volume, Length, Time', max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g., WEIGHT, VOLUME, LENGTH', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this unit type')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order in dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit Type',
                'verbose_name_plural': 'Unit Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_type__sort_order', 'unit_type__name', 'name']},
        ),
        migrations.RenameIndex(
            model_name='unit',
            new_name='products_un_unit_ty_494e41_idx',
            old_name='products_un_unit_ty_3fdeb7_idx',
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(help_text='Type of unit (Weight, Volume, Length, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='products.unittype'),
        ),
    ]
