# Generated by Django 6.0.2 on 2026-02-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_unittype_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='tags',
        ),
    ]
