# Generated by Django 6.0.2 on 2026-02-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_brand_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(help_text='Type of unit (Weight, Volume, Length, etc.)', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='products.unittype'),
        ),
    ]
