# Generated by Django 6.0.2 on 2026-02-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('weight', 'Weight (Mass)'), ('volume', 'Volume (Capacity)'), ('length', 'Length (Distance)'), ('area', 'Area (Surface Size)'), ('standard', 'Standard (Discrete)'), ('packaging', 'Primary Packaging'), ('time', 'Duration / Time'), ('digital', 'Digital Storage'), ('energy', 'Energy')], default='standard', help_text='Type of unit (Weight, Volume, Length, etc.)', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_type', 'name']},
        ),
        migrations.RenameIndex(
            model_name='unit',
            new_name='products_un_unit_ty_3fdeb7_idx',
            old_name='products_un_unit_ty_494e41_idx',
        ),
        migrations.DeleteModel(
            name='UnitType',
        ),
    ]
