# Generated by Django 6.0.2 on 2026-02-25 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_unittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Retail Price, Wholesale Price', max_length=100)),
                ('code', models.CharField(help_text='e.g., RETAIL, WHOLESALE', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower number = higher priority')),
                ('discount_method', models.CharField(choices=[('fixed', 'Fixed Price'), ('percentage', 'Percentage off base'), ('formula', 'Formula based')], default='fixed', max_length=20)),
                ('default_discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Default discount % for this price list', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default price list for new products')),
                ('applicable_to_retail', models.BooleanField(default=True)),
                ('applicable_to_wholesale', models.BooleanField(default=False)),
                ('applicable_to_distributor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for calculations', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='default_price_list',
            field=models.ForeignKey(blank=True, help_text='Default price list for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_products', to='products.pricelist'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this product in this price list', max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override the default discount % for this product', max_digits=5, null=True)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity to get this price')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_prices', to='products.product')),
            ],
            options={
                'ordering': ['product', 'price_list__priority', 'min_quantity'],
                'indexes': [models.Index(fields=['product', 'price_list'], name='products_pr_product_c0a594_idx'), models.Index(fields=['price_list', 'min_quantity'], name='products_pr_price_l_8fdcc6_idx')],
                'unique_together': {('product', 'price_list', 'min_quantity')},
            },
        ),
    ]
