# Generated by Django 6.0.2 on 2026-02-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pricelist_product_base_price_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'active'], name='products_pr_brand_i_514cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_number'], name='products_pr_model_n_bf8639_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_unit'], name='products_pr_base_un_ef888d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', 'active'], name='products_pr_created_839b0e_idx'),
        ),
    ]
