# Generated by Django 6.0.2 on 2026-02-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_fix_critical_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturing_date',
        ),
    ]
