# Generated by Django 6.0.2 on 2026-02-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_batch_info_from_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='stock_quantity_non_negative',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
