# Generated by Django 6.0.2 on 2026-02-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_settings', '0003_add_currency_to_product'),
        ('products', '0012_remove_product_stock_quantity_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for base price', null=True, on_delete=django.db.models.deletion.PROTECT, to='config_settings.currency'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for this price (defaults to product currency)', null=True, on_delete=django.db.models.deletion.PROTECT, to='config_settings.currency'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='exchange_rate_at_creation',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate when this price was set', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['currency'], name='products_pr_currenc_92522f_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['currency'], name='products_pr_currenc_fb7faf_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'currency'], name='products_pr_product_63a48b_idx'),
        ),
    ]
