# Generated by Django 6.0.2 on 2026-02-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_fix_productimage_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product',
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'is_primary'), name='unique_primary_image_per_product'),
        ),
    ]
