# Generated by Django 6.0.2 on 2026-02-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_productimage_unique_primary_image_per_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product',
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
    ]
