# Generated by Django 6.0.2 on 2026-02-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_productimage_unique_primary_image_per_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
